# Generated by Django 2.2.2 on 2019-06-06 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlineapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='college',
            name='contact',
            field=models.EmailField(default='a@b.com', max_length=254),
            preserve_default=False,
        ),
    ]
