# Generated by Django 2.2.2 on 2019-06-06 09:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('onlineapp', '0003_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='place',
            field=models.CharField(default=False, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='student',
            name='college',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='onlineapp.college'),
        ),
        migrations.AlterField(
            model_name='student',
            name='drop_out',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='marks_sheet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problem1', models.IntegerField(max_length=15)),
                ('problem2', models.IntegerField(max_length=15)),
                ('problem3', models.IntegerField(max_length=15)),
                ('name', models.CharField(max_length=30)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='onlineapp.student')),
            ],
        ),
    ]
