# Generated by Django 2.2.2 on 2019-06-06 10:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('onlineapp', '0004_auto_20190606_1525'),
    ]

    operations = [
        migrations.CreateModel(
            name='MockTest1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problem1', models.IntegerField()),
                ('problem2', models.IntegerField()),
                ('problem3', models.IntegerField()),
                ('problem4', models.IntegerField()),
                ('total', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
            ],
        ),
        migrations.RenameField(
            model_name='student',
            old_name='drop_out',
            new_name='dropped_out',
        ),
        migrations.RemoveField(
            model_name='student',
            name='place',
        ),
        migrations.AddField(
            model_name='student',
            name='db_folder',
            field=models.CharField(default='yashu1', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='email',
            field=models.EmailField(default='yashu2', max_length=254),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='college',
            name='acronym',
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name='college',
            name='location',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='college',
            name='name',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='student',
            name='college',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='onlineapp.College'),
        ),
        migrations.AlterField(
            model_name='student',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(max_length=128),
        ),
        migrations.DeleteModel(
            name='marks_sheet',
        ),
        migrations.AddField(
            model_name='teacher',
            name='college',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='onlineapp.College'),
        ),
        migrations.AddField(
            model_name='mocktest1',
            name='student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='onlineapp.Student'),
        ),
    ]
